services:
  - type: web
    name: evolution-api
    runtime: node
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
    buildCommand: npm install && npm run db:generate && npm run build
    startCommand: npm run db:deploy && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: SERVER_TYPE
        value: http
      - key: SERVER_PORT
        value: 8080
      - key: SERVER_URL
        sync: false
      - key: SERVER_DISABLE_DOCS
        value: "false"
      - key: SERVER_DISABLE_MANAGER
        value: "false"
      - key: AUTHENTICATION_API_KEY
        generateValue: true
      - key: AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES
        value: "false"
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolution-api-db
          property: connectionString
      - key: DATABASE_CONNECTION_CLIENT_NAME
        value: evolution
      - key: DATABASE_SAVE_DATA_INSTANCE
        value: "true"
      - key: DATABASE_SAVE_DATA_NEW_MESSAGE
        value: "true"
      - key: DATABASE_SAVE_MESSAGE_UPDATE
        value: "true"
      - key: DATABASE_SAVE_DATA_CONTACTS
        value: "true"
      - key: DATABASE_SAVE_DATA_CHATS
        value: "true"
      - key: DATABASE_SAVE_DATA_HISTORIC
        value: "true"
      - key: DATABASE_SAVE_DATA_LABELS
        value: "true"
      - key: DATABASE_SAVE_IS_ON_WHATSAPP
        value: "true"
      - key: DATABASE_SAVE_IS_ON_WHATSAPP_DAYS
        value: "7"
      - key: DATABASE_DELETE_MESSAGE
        value: "false"
      - key: CACHE_REDIS_ENABLED
        value: "true"
      - key: CACHE_REDIS_URI
        fromDatabase:
          name: evolution-api-redis
          property: connectionString
      - key: CACHE_REDIS_PREFIX_KEY
        value: evolution-cache
      - key: CACHE_REDIS_TTL
        value: "604800"
      - key: CACHE_REDIS_SAVE_INSTANCES
        value: "true"
      - key: CACHE_LOCAL_ENABLED
        value: "true"
      - key: CACHE_LOCAL_TTL
        value: "86400"
      - key: LOG_LEVEL
        value: "ERROR,WARN,INFO,LOG"
      - key: LOG_COLOR
        value: "true"
      - key: LOG_BAILEYS
        value: error
      - key: DEL_INSTANCE
        value: "false"
      - key: DEL_TEMP_INSTANCES
        value: "true"
      - key: LANGUAGE
        value: pt-BR
      - key: WEBSOCKET_ENABLED
        value: "true"
      - key: WEBSOCKET_GLOBAL_EVENTS
        value: "false"
      - key: CORS_ORIGIN
        value: "*"
      - key: CORS_METHODS
        value: POST,GET,PUT,DELETE
      - key: CORS_CREDENTIALS
        value: "true"

databases:
  - name: evolution-api-db
    plan: free
    region: frankfurt
    databaseName: evolution_api
    user: evolution_user

  - name: evolution-api-redis
    type: redis
    plan: free
    region: frankfurt
